version: "3"
services:
    react:
        container_name: react
        build: ./client
        ports: 
            - 3000:3000
        restart: unless-stopped
        env_file: 
            - .env
        volumes:
            - ./client/src:/app/src
    server:
        volumes:
            - ./server/src:/server/src
