version: "3"
services:
    client:
        build: 
            target: nginx-server
        ports: 
            - 3000:3000
        volumes:
            - ./client/src:/app/src
    server:
        volumes:
            - ./server/src:/server/src
