version: "3"
services:    
    db:
        container_name: db
        image: postgres
        restart: unless-stopped
        env_file: 
            - .env
        networks:
            - garden

    server:
        container_name: server
        build: ./server
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - garden

    client:
        container_name: client
        build: 
            context: ./client
        restart: unless-stopped
        env_file: 
            - .env
        networks:
            - garden

networks:
  garden:
    driver: bridge