version: "3"
services:
    client:
        build: 
            target: react-server
        ports: 
            - 3000:3000
        volumes:
            - ./client/src:/app/src
    server:
        ports:
            - 5000:5000
        volumes:
            - ./server/src:/server/src
networks:
  garden:
    driver: bridge
