version: "3"
services:
    react:
        container_name: react
        build: ./client
        ports: 
            - 3000:3000
        restart: unless-stopped
        env_file: 
            - .env
        volumes:
            - ./client/src:/app/src
    api:
        volumes:
            - ./api/app:/garden_palooza_be/app
    socket:
        volumes:
            - ./socket/src:/socket-server/src
