version: "3"
services: 
    api:
        container_name: api
        build: ./api
        ports: 
            - 80:80
        restart: unless-stopped
        env_file: 
            - .env
        depends_on:
            - db
    
    db:
        container_name: db
        image: postgres
        restart: unless-stopped
        env_file: 
            - .env

    socket:
        container_name: socket
        build: ./socket
        ports:
            - 5000:5000
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - db