version: "3"
services:    
    db:
        container_name: db
        image: postgres
        restart: unless-stopped
        env_file: 
            - .env
        networks:
            - garden

    server:
        container_name: server
        build: ./server
        ports:
            - 5000:5000
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - garden

networks:
  garden:
    driver: bridge