version: "3"
services:    
    db:
        container_name: db
        image: postgres
        restart: unless-stopped
        env_file: 
            - .env
        networks:
            - garden

    server:
        container_name: server
        build: ./server
        ports:
            - 5000:5000
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - garden
    
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        restart: unless-stopped
        ports: 
            - 3000:3000
        depends_on: 
            - prometheus
    
    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        restart: unless-stopped
        ports: 
            - 9090:9090
        command: 
            - --config.file=/etc/prometheus/prometheus.yml
        volumes: 
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on: 
            - cadvisor
    
    cadvisor:
        container_name: cadvisor
        image: grc.io/cadvisor/cavdisor:latest
        restart: unless-stopped
        ports: 
            - 8080:8080
        volumes: 
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro

networks:
  garden:
    driver: bridge